import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import type { CachedPersona } from "../cache/index.js";
import { type Config, paths } from "../config/index.js";
import type { Persona } from "../persona/index.js";
import { type LockEntry, Lock as LockSchema } from "../schema/index.js";

export interface AttachArgs {
  root: string;
  cached: CachedPersona;
  persona: Persona;
  source: string;
  commit: string;
  config: Config;
}

function isSymlink(p: string): boolean {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

/** Assemble the per-project dir: core symlink + scaffolded instance + lock entry + gitignore. */
export function attachPersona(a: AttachArgs): void {
  const name = a.cached.name;
  mkdirSync(join(paths.projectInstanceDir(a.root, name), "research"), { recursive: true });

  // core symlink → global current/core (gitignored, regenerated by sync)
  const coreLink = paths.projectCoreLink(a.root, name);
  if (existsSync(coreLink) || isSymlink(coreLink)) rmSync(coreLink, { force: true });
  symlinkSync(paths.currentCore(a.config, name), coreLink);

  // scaffold instance — PRESERVE an existing mandate/work (B2: never clobber your edits)
  const mandate = paths.projectMandate(a.root, name);
  if (!existsSync(mandate)) {
    writeFileSync(
      mandate,
      a.persona.instanceTemplate
        ? readFileSync(a.persona.instanceTemplate, "utf8")
        : `# Mandate — ${name}\n\nDescribe this project and what ${name} should do here.\n`,
    );
  }
  const work = paths.projectWork(a.root, name);
  if (!existsSync(work)) writeFileSync(work, `# ${name} — work log (grown lessons)\n`);

  // lock (read → merge → write)
  const lockPath = paths.projectLock(a.root);
  const lock = existsSync(lockPath)
    ? LockSchema.parse(JSON.parse(readFileSync(lockPath, "utf8")))
    : { version: 1 as const, personas: {} as Record<string, LockEntry> };
  lock.personas[name] = { source: a.source, version: a.cached.version, commit: a.commit };
  writeFileSync(lockPath, JSON.stringify(lock, null, 2));

  appendGitignore(a.root, ".truecast/agents/*/core");
}

function appendGitignore(root: string, line: string): void {
  const p = join(root, ".gitignore");
  const existing = existsSync(p) ? readFileSync(p, "utf8") : "";
  if (existing.split(/\r?\n/).includes(line)) return;
  const prefix = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
  writeFileSync(p, `${existing}${prefix}${line}\n`);
}
