import { existsSync, readFileSync, readlinkSync, realpathSync } from "node:fs";
import isPathInside from "is-path-inside";
import { type Config, paths } from "../config/index.js";
import { type Ledger, sha256 } from "../ledger/index.js";
import { readMeta } from "../meta/index.js";
import { readManifest } from "../persona/index.js";
import { isSymlink } from "../safety/index.js";
import { cachedVersions } from "../state/index.js";

/**
 * ADOPTION — the bridge between the two write lanes (D4; the tokens in these comments are defined in
 * docs/design/installer.md).
 *
 * The plugin lane (`bin/truecast-plugin.sh`) writes the same on-disk contract the CLI writes —
 * `<ver>/core`, `meta.json`, `current`, `<claudeHome>/agents/<name>.md` — but it cannot write
 * `owned.json` (that would mean a second implementation of `sha256Tree`'s framing, forever obliged to
 * match). Left alone, the next CLI op hits `ledger.guard()` and a plugin-installed persona becomes
 * permanently un-updatable by the CLI. So the CLI adopts what it can PROVE is truecast-shaped, and
 * nothing else: anything unattributable still raises `CollisionError` (B5 holds).
 *
 * Adoption records the OBSERVED bytes, so the following `assertWritable` sees `owns && !drifted` and the
 * op proceeds normally. Not folded into `Ledger.transaction`: this module imports `persona`/`state`/`meta`
 * and `ledger` must not depend on those. The protection is behavioral — see `adopt.test.ts`.
 */

/** A path that is provably truecast-shaped but absent from the ledger, plus how to record it. */
interface Adoptable {
  path: string;
  record: (ledger: Ledger) => void;
}

/** Is this cached version dir one truecast would have written? (contained + a manifest that agrees) */
function isTruecastCache(config: Config, core: string, name: string, ver: string): boolean {
  try {
    if (!isPathInside(realpathSync(core), realpathSync(config.truecastHome))) return false;
    const manifest = readManifest(core);
    return manifest.name === name && manifest.version === ver;
  } catch {
    return false; // unreadable / unparseable / escapes the home ⇒ not ours
  }
}

/** The stability-critical marker every generated agent file carries (D3) — never reword this substring. */
const GENERATED_MARKER = "GENERATED by truecast";

/**
 * How far into a file we look for the marker. The stamp sits under the frontmatter, so its line number
 * varies with how many optional keys the persona declares (`---`, name, description, model, tools,
 * `---`, blank, stamp = line 8 at most). 12 covers every shape with headroom while staying BOUNDED —
 * a mention of the marker deep inside someone's own notes must not make their file look generated.
 * `bin/truecast-plugin.sh` uses the same window (its `has_stamp` sed range); a fitness test asserts the
 * two numbers are equal, so this cannot drift.
 */
const STAMP_WINDOW_LINES = 12;

/** Does this file carry the generated stamp in its header window? (the same check the shell lane makes) */
function hasGeneratedStamp(path: string): boolean {
  try {
    return readFileSync(path, "utf8")
      .split("\n")
      .slice(0, STAMP_WINDOW_LINES)
      .join("\n")
      .includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * The attribution pass — PURE (reads only). One conservative predicate per managed kind; a path that
 * fails its predicate is simply not returned (and will collide later, as it should).
 * Throws only for a corrupt `meta.json`: R7 says that must stay visible, never be silently skipped.
 */
function scan(config: Config, name: string, ledger: Ledger): Adoptable[] {
  const found: Adoptable[] = [];

  // 1. cached version dirs — `<ver>/core` whose manifest names exactly this persona at this version.
  const attributed: string[] = [];
  for (const ver of cachedVersions(config, name)) {
    const core = paths.personaCache(config, name, ver);
    if (!isTruecastCache(config, core, name, ver)) continue;
    attributed.push(ver);
    if (!ledger.owns(core)) found.push({ path: core, record: (l) => l.recordDir(core, "cache") });
  }

  // 2. `current` — adoptable only when it points at one of those attributed versions.
  const link = paths.currentLink(config, name);
  if (!ledger.owns(link) && isSymlink(link)) {
    const target = readlinkSync(link);
    if (attributed.includes(target)) {
      found.push({
        path: link,
        // same shape promoteCurrent records: the hash of the relative target string
        record: (l) => l.record({ path: link, sha256: sha256(target), kind: "symlink" }),
      });
    }
  }

  // 3. meta.json — adoptable iff it parses as a PersonaMeta (a corrupt one throws; R7).
  const meta = paths.metaFile(config, name);
  if (!ledger.owns(meta) && existsSync(meta) && !isSymlink(meta) && readMeta(config, name)) {
    found.push({
      path: meta,
      record: (l) => l.record({ path: meta, sha256: sha256(readFileSync(meta)), kind: "meta" }),
    });
  }

  // 4. the agent file — adoptable iff it carries the generated stamp. A file WE didn't write is never
  //    adopted (that is exactly the FOREIGN case both lanes refuse to clobber).
  const agent = paths.claudeAgent(config, name);
  if (!ledger.owns(agent) && existsSync(agent) && !isSymlink(agent) && hasGeneratedStamp(agent)) {
    found.push({
      path: agent,
      record: (l) => l.record({ path: agent, sha256: sha256(readFileSync(agent)), kind: "agent" }),
    });
  }

  return found;
}

/**
 * The paths that WOULD be adopted, without recording anything — for `doctor`'s read-only inspect pass
 * (it reports them as the `unledgered` issue kind and heals them with `adoptUnledgered`).
 */
export function findUnledgered(config: Config, name: string, ledger: Ledger): string[] {
  return scan(config, name, ledger).map((a) => a.path);
}

/**
 * Adopt on-disk state that is provably truecast-shaped but not in the ledger (the plugin lane, or crash
 * residue from a pre-ledger version). Idempotent; returns the paths adopted. NEVER adopts a file we
 * can't attribute — those still raise CollisionError (B5 holds).
 */
export function adoptUnledgered(config: Config, name: string, ledger: Ledger): string[] {
  const adopted: string[] = [];
  for (const a of scan(config, name, ledger)) {
    a.record(ledger);
    adopted.push(a.path);
  }
  return adopted;
}
