import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  utimesSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import lockfile from "proper-lockfile";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import {
  type FakeHome,
  hasBash,
  makeClone,
  makeHome,
  runScript,
  writePersonaSource,
  writePlan,
} from "./fixture.js";

/**
 * The installer lane's behavior, driven through the real script against a synthetic marketplace clone
 * and a `mkdtemp` home (T-E1). Every §6 failure row gets a test here; the convergence invariant lives
 * in `convergence.test.ts`. Skipped — never failed — where bash isn't available (the lane is POSIX-only
 * by design; the command files say so and point at the npm CLI).
 */

const bash = hasBash();
let clone: string;
let fake: FakeHome;

beforeAll(() => {
  if (!bash) return;
  clone = makeClone([
    { name: "alpha", version: "1.0.0", tools: ["Read", "Grep"] },
    { name: "beta", version: "2.1.0", tools: ["Read"] },
  ]);
});
afterAll(() => {
  if (clone) rmSync(clone, { recursive: true, force: true });
});
beforeEach(() => {
  if (!bash) return;
  if (fake) rmSync(fake.home, { recursive: true, force: true });
  fake = makeHome();
});

const agent = (name: string): string => join(fake.claudeHome, "agents", `${name}.md`);
const personaDir = (name: string): string => join(fake.truecastHome, "personas", name);
const run = (...args: string[]) => runScript(clone, args, fake.env);

describe.skipIf(!bash)("install — plan, consent, apply", () => {
  it("without --yes it is PLAN ONLY: zero writes, and it says so", () => {
    const r = run("install", "alpha");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("plan");
    expect(r.result?.persona).toBe("alpha");
    expect(r.result?.version).toBe("1.0.0");
    expect(existsSync(fake.truecastHome)).toBe(false);
    expect(existsSync(fake.claudeHome)).toBe(false);
  });

  it("the plan surfaces the TOOL GRANT — the only place this lane shows it (D7)", () => {
    const r = run("install", "alpha");
    expect(r.stderr).toContain("tools granted to @alpha: Read, Grep");
    expect(r.stderr).toContain("nothing has been written yet");
  });

  it("--yes writes the body store, meta, pointer and agent file — agent LAST (G1)", () => {
    const r = run("install", "alpha", "--yes");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("installed");
    expect(existsSync(join(personaDir("alpha"), "1.0.0", "core", "persona.toml"))).toBe(true);
    expect(existsSync(join(personaDir("alpha"), "meta.json"))).toBe(true);
    expect(statSync(join(personaDir("alpha"), "current", "core")).isDirectory()).toBe(true);
    expect(readFileSync(agent("alpha"), "utf8")).toContain("GENERATED by truecast");
    // no owned.json: the ledger is the CLI's, and the CLI adopts what we wrote (D4)
    expect(existsSync(join(personaDir("alpha"), "owned.json"))).toBe(false);
  });

  it("substitutes the home token — no placeholder survives into a written file", () => {
    run("install", "alpha", "--yes");
    const body = readFileSync(agent("alpha"), "utf8");
    expect(body).not.toContain("{{TRUECAST_HOME}}");
    expect(body).toContain(`${fake.truecastHome}/personas/alpha/current/core/`);
  });

  it("is idempotent: a second install reports up-to-date and asks nothing", () => {
    run("install", "alpha", "--yes");
    const r = run("install", "alpha");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("up-to-date");
    expect(r.stderr).not.toContain("plan:");
  });

  it("leaves no staging or temp residue behind (T-F2)", () => {
    run("install", "alpha", "--yes");
    const stray: string[] = [];
    const walk = (dir: string): void => {
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        if (e.name.includes(".staging-") || e.name.includes(".tmp-")) stray.push(e.name);
        if (e.isDirectory()) walk(join(dir, e.name));
      }
    };
    walk(fake.home);
    expect(stray).toEqual([]);
  });

  it("writes the craft through a `.staging-` name the CLI's doctor already sweeps (T-F2)", () => {
    // the contract with `scanStale`: an interrupted copy can only leave `<ver>/core.staging-<pid>`
    const script = readFileSync(
      join(clone, "plugin", "truecast", "bin", "truecast-plugin.sh"),
      "utf8",
    );
    expect(script).toContain('STAGING="$vdir/core.staging-$$"');
    expect(script).toContain('cp "$WORK/body" "$target.tmp-$$"');
  });
});

describe.skipIf(!bash)("update", () => {
  /** A private clone, so bumping a version here can't leak into the shared fixture. */
  let bumped: string;
  const runBumped = (...args: string[]) => runScript(bumped, args, fake.env);

  beforeEach(() => {
    if (bumped) rmSync(bumped, { recursive: true, force: true });
    bumped = makeClone([{ name: "alpha", version: "1.0.0", tools: ["Read", "Grep"] }], "tc-bump-");
  });
  afterAll(() => {
    if (bumped) rmSync(bumped, { recursive: true, force: true });
  });

  const bumpTo = (version: string, skills?: string[]): void => {
    writePersonaSource(bumped, { name: "alpha", version, ...(skills ? { skills } : {}) });
    writePlan(bumped);
  };

  it("reports up-to-date when the clone matches what runs (no prompt)", () => {
    run("install", "alpha", "--yes");
    const r = run("update", "alpha");
    expect(r.result?.status).toBe("up-to-date");
    expect(r.result?.from).toBe("1.0.0");
  });

  it("plans a version span, then applies it with --force --yes", () => {
    runBumped("install", "alpha", "--yes");
    bumpTo("1.1.0", ["do-the-thing", "ship"]);

    const plan = runBumped("update", "alpha");
    expect(plan.result?.status).toBe("plan");
    expect(plan.result?.from).toBe("1.0.0");
    expect(plan.result?.version).toBe("1.1.0");
    expect(plan.result?.drift).toBe("true"); // the generated file differs ⇒ diff-and-ask
    expect(plan.stderr).toContain("@@"); // the unified diff the user must see

    const applied = runBumped("update", "alpha", "--force", "--yes");
    expect(applied.result?.status).toBe("updated");
    expect(readFileSync(agent("alpha"), "utf8")).toContain("ship");
    expect(existsSync(join(personaDir("alpha"), "1.1.0", "core"))).toBe(true);
    expect(existsSync(join(personaDir("alpha"), "1.0.0", "core"))).toBe(true); // old version kept
  });

  it("refuses to replace a differing generated file without --force (the consent round trip)", () => {
    runBumped("install", "alpha", "--yes");
    bumpTo("1.1.0");
    const r = runBumped("update", "alpha", "--yes");
    expect(r.status).toBe(7);
    expect(r.stderr).toContain("--force");
  });

  it("update on a persona that isn't installed exits 3 and points at install", () => {
    const r = run("update", "beta");
    expect(r.status).toBe(3);
    expect(r.stderr).toContain("/truecast:install beta");
  });

  it("--all reports one result line per persona and one failure never stops the rest", () => {
    run("install", "alpha", "--yes");
    run("install", "beta", "--yes");
    const r = run("update", "--all");
    expect(r.status).toBe(0);
    expect(r.stdout.match(/TRUECAST_RESULT/g)?.length).toBe(2);
    expect(r.stdout.trimEnd().split("\n").pop()).toContain("TRUECAST_RESULT");
  });

  it("--all with nothing installed is a clean noop", () => {
    const r = run("update", "--all");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("noop");
  });
});

describe.skipIf(!bash)("list", () => {
  it("shows installed vs available, the agent file scope, and the managing lane", () => {
    run("install", "alpha", "--yes");
    const r = run("list");
    expect(r.status).toBe(0);
    const row = r.stdout.split("\n").find((l) => l.startsWith("alpha")) ?? "";
    expect(row).toMatch(/alpha\s+1\.0\.0\s+1\.0\.0\s+user\s+plugin/);
    const beta = r.stdout.split("\n").find((l) => l.startsWith("beta")) ?? "";
    expect(beta).toMatch(/beta\s+-\s+2\.1\.0\s+-\s+-/);
  });

  it("reports `cli` once an ownership ledger sits alongside", () => {
    run("install", "alpha", "--yes");
    writeFileSync(join(personaDir("alpha"), "owned.json"), '{"version":1,"entries":[]}\n');
    const r = run("list");
    expect(r.stdout.split("\n").find((l) => l.startsWith("alpha"))).toContain("cli");
  });
});

describe.skipIf(!bash)("remove", () => {
  it("plans the exact deletions and the un-enumerable-dependents warning, writing nothing", () => {
    run("install", "alpha", "--yes");
    const r = run("remove", "alpha");
    expect(r.result?.status).toBe("plan");
    expect(r.stderr).toContain("every cached version");
    expect(r.stderr).toContain("cannot be enumerated");
    expect(existsSync(agent("alpha"))).toBe(true); // nothing removed
  });

  it("--yes removes the agent file first, then the whole body store", () => {
    run("install", "alpha", "--yes");
    const r = run("remove", "alpha", "--yes");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("removed");
    expect(existsSync(agent("alpha"))).toBe(false);
    expect(existsSync(personaDir("alpha"))).toBe(false);
  });

  it("removing something that isn't installed is a noop, not an error", () => {
    const r = run("remove", "beta");
    expect(r.status).toBe(0);
    expect(r.result?.status).toBe("noop");
  });

  it("keeps a foreign agent file, removes only the craft, and exits 5", () => {
    run("install", "alpha", "--yes");
    writeFileSync(agent("alpha"), "# my own alpha notes\n");
    const r = run("remove", "alpha", "--yes");
    expect(r.status).toBe(5);
    expect(r.result?.foreign).toBe("true");
    expect(readFileSync(agent("alpha"), "utf8")).toBe("# my own alpha notes\n"); // untouched
    expect(existsSync(personaDir("alpha"))).toBe(false);
  });
});

describe.skipIf(!bash)("§6 failure design", () => {
  it("T-F1: a held lock is BUSY (exit 4), not an interleaved write", () => {
    mkdirSync(join(fake.truecastHome, "personas"), { recursive: true });
    mkdirSync(join(fake.truecastHome, "personas", "alpha.lock"), { recursive: true });
    const r = run("install", "alpha", "--yes");
    expect(r.status).toBe(4);
    expect(existsSync(agent("alpha"))).toBe(false);
  });

  it("T-F1: the CLI's own lock blocks the script — one mechanism, not two (D9)", async () => {
    // taken through proper-lockfile itself, so this proves the two lanes agree on the lock PATH
    // (including its realpath canonicalisation), not merely on the convention
    mkdirSync(join(fake.truecastHome, "personas", "alpha"), { recursive: true });
    const release = await lockfile.lock(join(fake.truecastHome, "personas", "alpha"), {
      stale: 30_000,
    });
    try {
      const r = run("install", "alpha", "--yes");
      expect(r.status).toBe(4);
      expect(existsSync(agent("alpha"))).toBe(false);
    } finally {
      await release();
    }
    expect(run("install", "alpha", "--yes").status).toBe(0); // and it proceeds once released
  });

  it("T-F1: a lock older than 10 minutes is taken over, loudly (a kill must not wedge a user)", () => {
    const lock = join(fake.truecastHome, "personas", "alpha.lock");
    mkdirSync(lock, { recursive: true });
    const old = Date.now() / 1000 - 40 * 60;
    utimesSync(lock, old, old);
    const r = run("install", "alpha", "--yes");
    expect(r.status).toBe(0);
    expect(r.stderr).toContain("older than 10 minutes");
    expect(existsSync(agent("alpha"))).toBe(true);
  });

  it("T-F1: the lock is released — a second run is not blocked by the first", () => {
    run("install", "alpha", "--yes");
    expect(existsSync(join(fake.truecastHome, "personas", "alpha.lock"))).toBe(false);
    expect(run("install", "beta", "--yes").status).toBe(0);
  });

  it("T-F3: a dangling `current` is repaired by re-running install", () => {
    run("install", "alpha", "--yes");
    rmSync(join(personaDir("alpha"), "current"), { force: true });
    symlinkSync("9.9.9", join(personaDir("alpha"), "current"));
    const r = run("install", "alpha", "--yes");
    expect(r.status).toBe(0);
    expect(statSync(join(personaDir("alpha"), "current", "core")).isDirectory()).toBe(true);
  });

  it("T-F4: a clone that is not the truecast marketplace exits 3", () => {
    const notAClone = makeClone([{ name: "alpha", version: "1.0.0" }], "tc-notclone-");
    try {
      rmSync(join(notAClone, ".claude-plugin", "marketplace.json"), { force: true });
      const r = runScript(notAClone, ["install", "alpha"], fake.env);
      expect(r.status).toBe(3);
      expect(r.stderr).toContain("marketplace");
    } finally {
      rmSync(notAClone, { recursive: true, force: true });
    }
  });

  it("T-F4: a marketplace copy predating the installer says exactly how to fix it", () => {
    const old = makeClone([{ name: "alpha", version: "1.0.0" }], "tc-oldclone-");
    try {
      rmSync(join(old, "personas", "alpha", "subagent.md"), { force: true });
      const r = runScript(old, ["install", "alpha"], fake.env);
      expect(r.status).toBe(3);
      expect(r.stderr).toContain("/plugin marketplace update truecast");
    } finally {
      rmSync(old, { recursive: true, force: true });
    }
  });

  it("T-F4: an unknown persona exits 3", () => {
    const r = run("install", "nosuch");
    expect(r.status).toBe(3);
  });

  it("T-F5: a foreign agent file STOPS the install (exit 5) and --force does not override it", () => {
    mkdirSync(join(fake.claudeHome, "agents"), { recursive: true });
    writeFileSync(agent("alpha"), "# my own alpha teammate\n");
    for (const args of [
      ["install", "alpha"],
      ["install", "alpha", "--yes"],
      ["install", "alpha", "--force", "--yes"],
    ]) {
      const r = run(...args);
      expect(r.status, args.join(" ")).toBe(5);
      expect(r.result?.foreign).toBe("true");
    }
    expect(readFileSync(agent("alpha"), "utf8")).toBe("# my own alpha teammate\n");
    expect(existsSync(personaDir("alpha"))).toBe(false); // and nothing was written anywhere
  });

  it("T-F6/T-H2: an unset, relative or newline-bearing HOME is a precondition failure (exit 7)", () => {
    const base = { PATH: fake.env.PATH } as NodeJS.ProcessEnv;
    expect(runScript(clone, ["install", "alpha"], base).status).toBe(7);
    expect(runScript(clone, ["install", "alpha"], { ...base, HOME: "relative/home" }).status).toBe(
      7,
    );
    expect(runScript(clone, ["install", "alpha"], { ...base, HOME: "/tmp/a\nb" }).status).toBe(7);
    // a bad override is caught too, even when HOME itself is fine
    expect(
      runScript(clone, ["install", "alpha"], { ...base, HOME: fake.home, TRUECAST_HOME: "rel" })
        .status,
    ).toBe(7);
  });

  it("T-F7: git being unusable degrades to a path source + `local` commit; never fatal", () => {
    const shim = join(fake.home, "shim");
    mkdirSync(shim, { recursive: true });
    writeFileSync(join(shim, "git"), "#!/bin/sh\nexit 127\n");
    chmodSync(join(shim, "git"), 0o755);
    const r = runScript(clone, ["install", "alpha", "--yes"], {
      ...fake.env,
      PATH: `${shim}:${fake.env.PATH}`,
    });
    expect(r.status).toBe(0);
    const meta = JSON.parse(readFileSync(join(personaDir("alpha"), "meta.json"), "utf8"));
    expect(meta.source).toBe(`${clone}#personas/alpha`);
    expect(meta.versions[0].commit).toBe("local");
  });

  it("T-F8: restart is reported when we created the agents dir, and the hint is always printed", () => {
    const first = run("install", "alpha", "--yes");
    expect(first.result?.restart).toBe("true");
    expect(first.stderr).toContain("restart Claude Code once");

    const second = run("install", "beta", "--yes"); // the dir now exists
    expect(second.result?.restart).toBe("false");
    expect(second.stderr).toContain("restart Claude Code once");
  });

  it("T-S1: a hostile persona name never reaches the filesystem (exit 2)", () => {
    for (const name of ["../evil", "a;rm -rf /", "/etc/passwd", ".", "UPPER", "trailing-"]) {
      const r = run("install", name, "--yes");
      expect(r.status, name).toBe(2);
    }
    expect(existsSync(fake.truecastHome)).toBe(false);
    expect(existsSync(fake.claudeHome)).toBe(false);
  });

  it("T-S2: a symlink planted at the agent target is refused; its target is untouched", () => {
    const victim = join(fake.home, "victim.txt");
    writeFileSync(victim, "ORIGINAL");
    mkdirSync(join(fake.claudeHome, "agents"), { recursive: true });
    symlinkSync(victim, agent("alpha"));
    const r = run("install", "alpha", "--force", "--yes");
    expect(r.status).toBe(5);
    expect(readFileSync(victim, "utf8")).toBe("ORIGINAL");
  });

  it("T-S2: a symlink planted at the version dir's core is refused", () => {
    const victim = join(fake.home, "outside");
    mkdirSync(victim, { recursive: true });
    mkdirSync(join(personaDir("alpha"), "1.0.0"), { recursive: true });
    symlinkSync(victim, join(personaDir("alpha"), "1.0.0", "core"));
    const r = run("install", "alpha", "--yes");
    expect(r.status).toBe(7);
    expect(readdirSync(victim)).toEqual([]);
  });

  it("usage errors exit 2 and write nothing", () => {
    expect(run("install").status).toBe(2);
    expect(run("frobnicate").status).toBe(2);
    expect(run("install", "alpha", "--nope").status).toBe(2);
    expect(existsSync(fake.truecastHome)).toBe(false);
  });
});

describe.skipIf(!bash)("T-E2: --project scope (D8)", () => {
  let project: string;

  beforeEach(() => {
    project = join(fake.home, "myapp");
    mkdirSync(join(project, ".git"), { recursive: true });
  });

  const projectAgent = (): string => join(project, ".claude", "agents", "alpha.md");
  const projectMandate = (): string =>
    join(project, ".truecast", "agents", "alpha", "instance", "mandate.md");

  it("writes the project agent file plus the shared global body store", () => {
    const r = runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    expect(r.status).toBe(0);
    expect(existsSync(projectAgent())).toBe(true);
    expect(existsSync(agent("alpha"))).toBe(false); // user scope untouched
    expect(existsSync(join(personaDir("alpha"), "1.0.0", "core"))).toBe(true);
  });

  it("gitignores the machine-local file, exactly once", () => {
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    const gi = readFileSync(join(project, ".gitignore"), "utf8");
    expect(gi.split("\n").filter((l) => l === ".claude/agents/alpha.md").length).toBe(1);
  });

  it("scaffolds the mandate only when absent — never over an edit", () => {
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    expect(readFileSync(projectMandate(), "utf8")).toContain("Mandate — alpha");
    writeFileSync(projectMandate(), "# MY BRIEF\n");
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    expect(readFileSync(projectMandate(), "utf8")).toBe("# MY BRIEF\n");
  });

  it("writes NO project lock entry (named, accepted: invisible to `list --project`)", () => {
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    expect(existsSync(join(project, ".truecast", "lock"))).toBe(false);
  });

  it("remove --project DETACHES: the shared craft and the user-scope teammate survive", () => {
    runScript(clone, ["install", "alpha", "--yes"], fake.env);
    runScript(clone, ["install", "alpha", "--project", project, "--yes"], fake.env);
    const r = runScript(clone, ["remove", "alpha", "--project", project, "--yes"], fake.env);
    expect(r.status).toBe(0);
    expect(existsSync(projectAgent())).toBe(false);
    // deleting the shared body store here would leave the user-scope teammate pointing at nothing
    expect(existsSync(join(personaDir("alpha"), "1.0.0", "core"))).toBe(true);
    expect(existsSync(agent("alpha"))).toBe(true);
  });

  it("remove --project on a repo that has no project file is a noop", () => {
    runScript(clone, ["install", "alpha", "--yes"], fake.env);
    const r = runScript(clone, ["remove", "alpha", "--project", project], fake.env);
    expect(r.result?.status).toBe("noop");
    expect(existsSync(agent("alpha"))).toBe(true);
  });
});
