import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { CachedPersona } from "../cache/index.js";
import { type Config, paths } from "../config/index.js";
import type { Ledger, WriteOptions } from "../ledger/index.js";
import type { Persona } from "../persona/index.js";

const STAMP = "<!-- GENERATED by truecast — edit instance/, regenerate with `truecast sync`. -->";
const MAX_SUMMARY = 220;

const oneLine = (s: string): string => s.replace(/\s+/g, " ").trim().slice(0, MAX_SUMMARY);

/** A corpus file's display name + one-line summary: from SKILL.md frontmatter, else its lead line. */
function harvest(absPath: string): { name?: string; summary: string } {
  let text: string;
  try {
    text = readFileSync(absPath, "utf8");
  } catch {
    return { summary: "(unreadable)" };
  }
  let name: string | undefined;
  let description: string | undefined;
  let body = text;
  const fm = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (fm) {
    body = text.slice(fm[0].length);
    for (const line of (fm[1] ?? "").split("\n")) {
      const kv = line.match(/^(\w+):\s*(.*)$/);
      if (!kv) continue;
      const val = (kv[2] ?? "").trim().replace(/^["']|["']$/g, "");
      if (kv[1] === "name") name = val;
      else if (kv[1] === "description") description = val;
    }
  }
  if (description) return { name, summary: oneLine(description) };
  // no frontmatter description — fall back to the first prose line, else the first heading
  let heading: string | undefined;
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#")) {
      heading ??= line.replace(/^#+\s*/, "");
      continue;
    }
    return { name, summary: oneLine(line) };
  }
  return { name, summary: heading ? oneLine(heading) : "(no description)" };
}

/** Display name for a corpus entry: frontmatter `name`, else the skill dir / knowledge filename. */
function entryName(rel: string, fmName?: string): string {
  if (fmName) return fmName;
  const parts = rel.split("/");
  const last = parts[parts.length - 1] ?? rel;
  if (/^skill\.md$/i.test(last) && parts.length >= 2) return parts[parts.length - 2] as string;
  return last.replace(/\.md$/i, "");
}

/**
 * Compose a persona's SYSTEM PROMPT — identity + a capability index (each skill/knowledge file with a
 * one-line summary and the path to Read) + where its job lives. TRANSPORT-AGNOSTIC and the single owner
 * of "what a persona's prompt says": `materialize` writes it into the `@subagent` file, and the (future)
 * standalone-session launcher feeds the SAME string to `claude --append-system-prompt-file`. The index
 * lives here (always-loaded) because a subagent has no Skill tool and `persona.toml` carries no
 * descriptions — so this is how the persona learns what craft it has and to Read it before applying.
 */
/**
 * UNIVERSAL operating craft injected into EVERY persona's prompt — the engine owns this, not the
 * publisher (it's not in any `core/`) and not the user (it's not in any `mandate.md`). It is deliberately
 * tiny, stable, and behavioral-hygiene only (read-first / ground-in-reality / verify) plus the one
 * truecast-specific navigation reflex. It is NOT project judgment ("the bar," "what's worth the effort")
 * — that lives in the founder-owned mandate. Because the whole rendered prompt is inspectable
 * (`truecast prompt <name>`) and re-rendered on `truecast update`, changing this is a visible, diffable
 * event — not the silent base-prompt change that burns trust. Keep it stable; don't iterate it like a
 * feature. The `principles.conformance.test.ts` asserts every shipped persona renders with this block.
 */
export const ENGINE_PRINCIPLES = `## How you work
- **Read before you act** — open your \`core/\` skills and the actual project files and code first; never answer from memory or assumption.
- **Ground every claim in what you can see** — point to the file, the code, the source; if you don't know, find out rather than guess.
- **Verify before you call it done** — check it against reality, never state as fact what you haven't confirmed, and never invent a result.`;

export function renderSystemPrompt(cached: CachedPersona, persona: Persona): string {
  const name = cached.name;
  const m = persona.manifest;
  const base = `.truecast/agents/${name}`; // resolved against the project root at runtime
  const identity = readFileSync(join(cached.coreDir, m.identity), "utf8").trim();

  const index = (rels: readonly string[]): string =>
    rels
      .map((rel) => {
        const { name: fmName, summary } = harvest(join(cached.coreDir, rel));
        return `- **${entryName(rel, fmName)}** — ${summary}  → Read \`${base}/core/${rel}\``;
      })
      .join("\n");

  const sections: string[] = [identity];
  if (m.skills.length > 0) {
    sections.push(
      `## Your skills\nThis is your craft. When a task matches one, **Read that file first**, then apply it — these are files you Read through the \`core/\` symlink, not slash-commands.\n\n${index(m.skills)}`,
    );
  }
  if (m.knowledge.length > 0) {
    sections.push(
      `## Your knowledge\nReference material — Read when relevant.\n\n${index(m.knowledge)}`,
    );
  }
  sections.push(ENGINE_PRINCIPLES);
  sections.push(
    `## Your job in this project\nRead \`${base}/instance/mandate.md\` for what to do here, and \`${base}/instance/work.md\` for accumulated lessons. A direct \`Read\` is transparent through the symlink; to search, target \`${base}/core/\` and \`${base}/instance/\` explicitly (a bare \`rg .\` misses the symlinked core).`,
  );
  return sections.join("\n\n");
}

/**
 * Generate the Claude Code `@subagent` surface: `~/.claude/agents/<name>.md` = frontmatter + the
 * composed system prompt. Skills/knowledge are NOT copied anywhere — they are the persona's private
 * craft, Read on demand from the symlinked `core/` (the body indexes them). Legacy `~/.claude/skills`
 * copies a prior version made are swept here.
 */
export function materialize(
  cached: CachedPersona,
  persona: Persona,
  config: Config,
  ledger: Ledger,
  opts: WriteOptions = {},
): void {
  const name = cached.name;
  const m = persona.manifest;
  const frontmatter = [
    "---",
    `name: ${name}`,
    `description: ${m.description ?? `The ${name} persona.`}`,
    ...(m.modelHint ? [`model: ${m.modelHint}`] : []),
    ...(m.tools && m.tools.length > 0 ? [`tools: ${m.tools.join(", ")}`] : []),
    "---",
  ].join("\n");

  const body = `${frontmatter}\n\n${STAMP}\n\n${renderSystemPrompt(cached, persona)}\n`;
  ledger.writeFile(paths.claudeAgent(config, name), body, "agent", opts);

  // sweep any legacy ~/.claude/skills copies a prior truecast version installed (now inert for subagents)
  for (const e of ledger.owned()) {
    if (e.kind === "skill") ledger.removeOwned(e.path);
  }
}
