import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { CachedPersona } from "../cache/index.js";
import { type Config, paths } from "../config/index.js";
import type { Ledger, WriteOptions } from "../ledger/index.js";
import type { Persona } from "../persona/index.js";

const STAMP = "<!-- GENERATED by truecast — edit instance/, regenerate with `truecast sync`. -->";
const MAX_SUMMARY = 220;

const oneLine = (s: string): string => s.replace(/\s+/g, " ").trim().slice(0, MAX_SUMMARY);

/** A corpus file's display name + one-line summary: from SKILL.md frontmatter, else its lead line. */
function harvest(absPath: string): { name?: string; summary: string } {
  let text: string;
  try {
    text = readFileSync(absPath, "utf8");
  } catch {
    return { summary: "(unreadable)" };
  }
  let name: string | undefined;
  let description: string | undefined;
  let body = text;
  const fm = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (fm) {
    body = text.slice(fm[0].length);
    for (const line of (fm[1] ?? "").split("\n")) {
      const kv = line.match(/^(\w+):\s*(.*)$/);
      if (!kv) continue;
      const val = (kv[2] ?? "").trim().replace(/^["']|["']$/g, "");
      if (kv[1] === "name") name = val;
      else if (kv[1] === "description") description = val;
    }
  }
  if (description) return { name, summary: oneLine(description) };
  // no frontmatter description — fall back to the first prose line, else the first heading
  let heading: string | undefined;
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#")) {
      heading ??= line.replace(/^#+\s*/, "");
      continue;
    }
    return { name, summary: oneLine(line) };
  }
  return { name, summary: heading ? oneLine(heading) : "(no description)" };
}

/** Display name for a corpus entry: frontmatter `name`, else the skill dir / knowledge filename. */
function entryName(rel: string, fmName?: string): string {
  if (fmName) return fmName;
  const parts = rel.split("/");
  const last = parts[parts.length - 1] ?? rel;
  if (/^skill\.md$/i.test(last) && parts.length >= 2) return parts[parts.length - 2] as string;
  return last.replace(/\.md$/i, "");
}

/**
 * Where a rendered prompt will run — picks the craft path scheme and the job-section prose. A required,
 * no-default param on `renderSystemPrompt` so every caller declares its transport (no silent drift):
 * - `subagent`: craft is Read through the project `.truecast/agents/<name>/core` SYMLINK (the CLI surface).
 * - `plugin`: craft is bundled in the plugin and Read via `${CLAUDE_PLUGIN_ROOT}/core` (no symlink); the
 *   per-project mandate may not exist yet, so the job section tells the persona to establish it first.
 * The job/instance path is project-relative for BOTH — the job lives in the consuming repo, never in the
 * read-only plugin. A two-member discriminated union (not an enum): adding a transport is a typed change.
 */
export type PromptTransport = { kind: "subagent" } | { kind: "plugin" };

/**
 * UNIVERSAL operating craft injected into EVERY persona's prompt — the engine owns this, not the
 * publisher (it's not in any `core/`) and not the user (it's not in any `mandate.md`). It is deliberately
 * tiny, stable, and behavioral-hygiene only (read-first / ground-in-reality / verify) plus the one
 * truecast-specific navigation reflex. It is NOT project judgment ("the bar," "what's worth the effort")
 * — that lives in the founder-owned mandate. Because the whole rendered prompt is inspectable
 * (`truecast prompt <name>`) and re-rendered on `truecast update`, changing this is a visible, diffable
 * event — not the silent base-prompt change that burns trust. Keep it stable; don't iterate it like a
 * feature. The `principles.conformance.test.ts` asserts every shipped persona renders with this block.
 */
export const ENGINE_PRINCIPLES = `## How you work
- **Read before you act** — open your \`core/\` skills and the actual project files and code first; never answer from memory or assumption.
- **Ground every claim in what you can see** — point to the file, the code, the source; if you don't know, find out rather than guess.
- **Verify before you call it done** — check it against reality, never state as fact what you haven't confirmed, and never invent a result.`;

/**
 * Compose a persona's SYSTEM PROMPT — identity + a capability index (each skill/knowledge file with a
 * one-line summary and the path to Read) + where its job lives. The single owner of "what a persona's
 * prompt says", across every transport: `materialize` writes it into the `@subagent` file, `publish`
 * bakes it into the plugin agent body, and `truecast prompt` feeds it to `claude --append-system-prompt`.
 * The index lives here (always-loaded) because a subagent has no Skill tool and `persona.toml` carries no
 * descriptions — so this is how the persona learns what craft it has and to Read it before applying.
 */
export function renderSystemPrompt(
  cached: CachedPersona,
  persona: Persona,
  transport: PromptTransport,
): string {
  const name = cached.name;
  const m = persona.manifest;
  // The job/instance dir is project-relative for both transports (the job lives in the consuming repo).
  const instanceBase = `.truecast/agents/${name}/instance`;
  // The craft dir differs by transport: the project symlink vs the bundled plugin root.
  // biome-ignore lint/suspicious/noTemplateCurlyInString: a LITERAL token Claude Code interpolates at the installer's runtime — not ours to expand.
  const PLUGIN_CRAFT = "${CLAUDE_PLUGIN_ROOT}/core";
  const craftBase = transport.kind === "plugin" ? PLUGIN_CRAFT : `.truecast/agents/${name}/core`;
  const identity = readFileSync(join(cached.coreDir, m.identity), "utf8").trim();

  const index = (rels: readonly string[]): string =>
    rels
      .map((rel) => {
        const { name: fmName, summary } = harvest(join(cached.coreDir, rel));
        return `- **${entryName(rel, fmName)}** — ${summary}  → Read \`${craftBase}/${rel}\``;
      })
      .join("\n");

  // The one place the symlink shows up in prose — false on the plugin transport (bundled real dir).
  const howRead = transport.kind === "plugin" ? "on demand" : "through the `core/` symlink";

  const sections: string[] = [identity];
  if (m.skills.length > 0) {
    sections.push(
      `## Your skills\nThis is your craft. When a task matches one, **Read that file first**, then apply it — these are files you Read ${howRead}, not slash-commands.\n\n${index(m.skills)}`,
    );
  }
  if (m.knowledge.length > 0) {
    sections.push(
      `## Your knowledge\nReference material — Read when relevant.\n\n${index(m.knowledge)}`,
    );
  }
  sections.push(ENGINE_PRINCIPLES);
  sections.push(
    transport.kind === "plugin"
      ? `## Your job in this project\nWork from the user's brief for this project if they've given you one — a \`${instanceBase}/mandate.md\`, a \`CLAUDE.md\`, or direction in this conversation. **If there's no brief, that's not an error: ask the user what they need from you here, then proceed from your craft.** For a standing mandate that persists across sessions, they can install you with the \`truecast\` CLI; you run fine without it.`
      : `## Your job in this project\nRead \`${instanceBase}/mandate.md\` for what to do here, and \`${instanceBase}/work.md\` for accumulated lessons. A direct \`Read\` is transparent through the symlink; to search, target \`${craftBase}/\` and \`${instanceBase}/\` explicitly (a bare \`rg .\` misses the symlinked core).`,
  );
  return sections.join("\n\n");
}

/**
 * Collapse a value to a single safe frontmatter line — defeats a persona that smuggles a newline into a
 * field (e.g. `description`/`modelHint`) to forge extra YAML keys like a wider `tools:` grant. The
 * frontmatter is line-oriented, so NO value may contain a line break (schema `noControlChars` is the
 * first line of defense; this is belt-and-suspenders at the only place values become frontmatter).
 */
const oneFrontmatterLine = (s: string): string => s.replace(/[\r\n]+/g, " ").trim();

/**
 * The complete agent `.md` file (frontmatter + STAMP + system prompt) for a transport. The single owner
 * of the agent-file shape: `materialize` writes this to `~/.claude/agents/<name>.md` (subagent transport),
 * and `publish` bakes it into the plugin's `agents/<name>.md` (plugin transport). The frontmatter carries
 * the persona's `tools`/`model` so BOTH surfaces declare least-privilege the same way (on the plugin path,
 * this list is what Claude Code surfaces to the user — truecast's own tool-grant confirm doesn't run there).
 */
export function composeAgentFile(
  cached: CachedPersona,
  persona: Persona,
  transport: PromptTransport,
): string {
  const name = cached.name;
  const m = persona.manifest;
  const frontmatter = [
    "---",
    `name: ${name}`,
    `description: ${oneFrontmatterLine(m.description ?? `The ${name} persona.`)}`,
    ...(m.modelHint ? [`model: ${oneFrontmatterLine(m.modelHint)}`] : []),
    ...(m.tools && m.tools.length > 0 ? [`tools: ${m.tools.join(", ")}`] : []),
    "---",
  ].join("\n");
  return `${frontmatter}\n\n${STAMP}\n\n${renderSystemPrompt(cached, persona, transport)}\n`;
}

/**
 * Generate the Claude Code `@subagent` surface: `~/.claude/agents/<name>.md` = frontmatter + the
 * composed system prompt. Skills/knowledge are NOT copied anywhere — they are the persona's private
 * craft, Read on demand from the symlinked `core/` (the body indexes them). Legacy `~/.claude/skills`
 * copies a prior version made are swept here.
 */

export function materialize(
  cached: CachedPersona,
  persona: Persona,
  config: Config,
  ledger: Ledger,
  opts: WriteOptions = {},
): void {
  const name = cached.name;
  const body = composeAgentFile(cached, persona, { kind: "subagent" });
  ledger.writeFile(paths.claudeAgent(config, name), body, "agent", opts);

  // sweep any legacy ~/.claude/skills copies a prior truecast version installed (now inert for subagents)
  for (const e of ledger.owned()) {
    if (e.kind === "skill") ledger.removeOwned(e.path);
  }
}
