import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { CachedPersona } from "../cache/index.js";
import { type Config, paths } from "../config/index.js";
import type { Ledger, WriteOptions } from "../ledger/index.js";
import type { Persona } from "../persona/index.js";

const MAX_SUMMARY = 220;

/**
 * The two-line stamp at the head of every generated agent file. Line 1 carries the STABILITY-CRITICAL
 * marker `GENERATED by truecast` — 0.2.x files carry it, and both lanes' "did truecast write this?"
 * check keys off that substring (D3 / one-way door 6). Never reword it. Line 2 carries the version so
 * drift and migration can be reasoned about from the file alone.
 */
function stamp(name: string, version: string): string {
  return [
    "<!-- GENERATED by truecast — edit instance/mandate.md, not this file. -->",
    `<!-- truecast: ${name}@${version} — regenerate with \`truecast update ${name}\` or \`/truecast:update ${name}\`. -->`,
  ].join("\n");
}

/**
 * The token the published subagent TEMPLATE carries in place of a real home. The installer replaces it
 * with the user's real `~/.truecast` at write time; it must never survive into a written agent file.
 */
export const TRUECAST_HOME_PLACEHOLDER = "{{TRUECAST_HOME}}";

const oneLine = (s: string): string => s.replace(/\s+/g, " ").trim().slice(0, MAX_SUMMARY);

/** A corpus file's display name + one-line summary: from SKILL.md frontmatter, else its lead line. */
function harvest(absPath: string): { name?: string; summary: string } {
  let text: string;
  try {
    text = readFileSync(absPath, "utf8");
  } catch {
    return { summary: "(unreadable)" };
  }
  let name: string | undefined;
  let description: string | undefined;
  let body = text;
  const fm = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (fm) {
    body = text.slice(fm[0].length);
    for (const line of (fm[1] ?? "").split("\n")) {
      const kv = line.match(/^(\w+):\s*(.*)$/);
      if (!kv) continue;
      const val = (kv[2] ?? "").trim().replace(/^["']|["']$/g, "");
      if (kv[1] === "name") name = val;
      else if (kv[1] === "description") description = val;
    }
  }
  if (description) return { name, summary: oneLine(description) };
  // no frontmatter description — fall back to the first prose line, else the first heading
  let heading: string | undefined;
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#")) {
      heading ??= line.replace(/^#+\s*/, "");
      continue;
    }
    return { name, summary: oneLine(line) };
  }
  return { name, summary: heading ? oneLine(heading) : "(no description)" };
}

/** Display name for a corpus entry: frontmatter `name`, else the skill dir / knowledge filename. */
function entryName(rel: string, fmName?: string): string {
  if (fmName) return fmName;
  const parts = rel.split("/");
  const last = parts[parts.length - 1] ?? rel;
  if (/^skill\.md$/i.test(last) && parts.length >= 2) return parts[parts.length - 2] as string;
  return last.replace(/\.md$/i, "");
}

/**
 * Where a rendered prompt will run — picks the craft path scheme and the job-section prose. A required,
 * no-default param on `renderSystemPrompt` so every caller declares its transport (no silent drift):
 * - `subagent`: craft is Read at an ABSOLUTE path into the global store,
 *   `<truecastHome>/personas/<name>/current/core` — so the teammate works from ANY project, not only one
 *   it was attached to. `truecastHome` is the absolute home of the target machine, or
 *   `TRUECAST_HOME_PLACEHOLDER` when rendering the published template the installer substitutes into.
 * - `plugin`: craft is bundled in the plugin and Read via `${CLAUDE_PLUGIN_ROOT}/core`; the per-project
 *   mandate may not exist yet, so the job section makes its absence a non-error.
 * The job/instance path is project-relative for BOTH — the job lives in the consuming repo, never in the
 * read-only plugin. A two-member discriminated union (not an enum): adding a transport is a typed change.
 */
export type PromptTransport = { kind: "subagent"; truecastHome: string } | { kind: "plugin" };

/**
 * UNIVERSAL operating craft injected into EVERY persona's prompt — the engine owns this, not the
 * publisher (it's not in any `core/`) and not the user (it's not in any `mandate.md`). It is deliberately
 * tiny, stable, and behavioral-hygiene only (read-first / ground-in-reality / verify) plus the one
 * truecast-specific navigation reflex. It is NOT project judgment ("the bar," "what's worth the effort")
 * — that lives in the founder-owned mandate. Because the whole rendered prompt is inspectable
 * (`truecast prompt <name>`) and re-rendered on `truecast update`, changing this is a visible, diffable
 * event — not the silent base-prompt change that burns trust. Keep it stable; don't iterate it like a
 * feature. The `principles.conformance.test.ts` asserts every shipped persona renders with this block.
 */
export const ENGINE_PRINCIPLES = `## How you work
- **Read before you act** — open your \`core/\` skills and the actual project files and code first; never answer from memory or assumption.
- **Ground every claim in what you can see** — point to the file, the code, the source; if you don't know, find out rather than guess.
- **Verify before you call it done** — check it against reality, never state as fact what you haven't confirmed, and never invent a result.`;

/**
 * Compose a persona's SYSTEM PROMPT — identity + a capability index (each skill/knowledge file with a
 * one-line summary and the path to Read) + where its job lives. The single owner of "what a persona's
 * prompt says", across every transport: `materialize` writes it into the `@subagent` file, `publish`
 * bakes it into the plugin agent body, and `truecast prompt` feeds it to `claude --append-system-prompt`.
 * The index lives here (always-loaded) because a subagent has no Skill tool and `persona.toml` carries no
 * descriptions — so this is how the persona learns what craft it has and to Read it before applying.
 */
export function renderSystemPrompt(
  cached: CachedPersona,
  persona: Persona,
  transport: PromptTransport,
): string {
  const name = cached.name;
  const m = persona.manifest;
  // The job/instance dir is project-relative for both transports (the job lives in the consuming repo).
  const instanceBase = `.truecast/agents/${name}/instance`;
  // The craft dir differs by transport: the bundled plugin root vs an absolute path into the global
  // store. POSIX-concatenated with `/`, never `path.join` — a Windows-rendered `\` would corrupt the
  // file and break byte-identity between the two lanes (D1).
  // biome-ignore lint/suspicious/noTemplateCurlyInString: a LITERAL token Claude Code interpolates at the installer's runtime — not ours to expand.
  const PLUGIN_CRAFT = "${CLAUDE_PLUGIN_ROOT}/core";
  const craftBase =
    transport.kind === "plugin"
      ? PLUGIN_CRAFT
      : `${transport.truecastHome}/personas/${name}/current/core`;
  const identity = readFileSync(join(cached.coreDir, m.identity), "utf8").trim();

  const index = (rels: readonly string[]): string =>
    rels
      .map((rel) => {
        const { name: fmName, summary } = harvest(join(cached.coreDir, rel));
        return `- **${entryName(rel, fmName)}** — ${summary}  → Read \`${craftBase}/${rel}\``;
      })
      .join("\n");

  // Where the index says these files come from — bundled with the plugin, or the global install.
  const howRead = transport.kind === "plugin" ? "on demand" : "from your global truecast install";

  const sections: string[] = [identity];
  if (m.skills.length > 0) {
    sections.push(
      `## Your skills\nThis is your craft. When a task matches one, **Read that file first**, then apply it — these are files you Read ${howRead}, not slash-commands.\n\n${index(m.skills)}`,
    );
  }
  if (m.knowledge.length > 0) {
    sections.push(
      `## Your knowledge\nReference material — Read when relevant.\n\n${index(m.knowledge)}`,
    );
  }
  sections.push(ENGINE_PRINCIPLES);
  sections.push(
    transport.kind === "plugin"
      ? `## Your job in this project\nWork from the user's brief for this project if they've given you one — a \`${instanceBase}/mandate.md\`, a \`CLAUDE.md\`, or direction in this conversation. **If there's no brief, that's not an error: ask the user what they need from you here, then proceed from your craft.** For a standing mandate that persists across sessions, they can install you with the \`truecast\` CLI; you run fine without it.`
      : // The absolute-pointer overlay (D1), verbatim: the craft is global, the job is per-repo, and a
        // repo with no brief is a normal state — not a failure the persona should report as one.
        `## Your job in this project
Your craft lives at \`${craftBase}/\` — an absolute path that works from
any project, so Read those files directly. A bare \`rg .\` in the repo will not reach them; search that
path explicitly when you need to.

**This repo's brief, if it has one.** If \`${instanceBase}/mandate.md\` exists in the
current working directory, Read it FIRST — it is your standing mandate here and it overrides your
general defaults wherever they differ. Read \`${instanceBase}/work.md\` too if it exists
(lessons from past work in this repo). If neither exists, that is not an error: take direction from this
conversation, and ask the user what they need from you here if it isn't clear.`,
  );
  return sections.join("\n\n");
}

/**
 * Collapse a value to a single safe frontmatter line — defeats a persona that smuggles a newline into a
 * field (e.g. `description`/`modelHint`) to forge extra YAML keys like a wider `tools:` grant. The
 * frontmatter is line-oriented, so NO value may contain a line break (schema `noControlChars` is the
 * first line of defense; this is belt-and-suspenders at the only place values become frontmatter).
 */
const oneFrontmatterLine = (s: string): string => s.replace(/[\r\n]+/g, " ").trim();

/**
 * The complete agent `.md` file (frontmatter + STAMP + system prompt) for a transport. The single owner
 * of the agent-file shape: `materialize` writes this to `~/.claude/agents/<name>.md` (subagent transport),
 * and `publish` bakes it into the plugin's `agents/<name>.md` (plugin transport). The frontmatter carries
 * the persona's `tools`/`model` so BOTH surfaces declare least-privilege the same way (on the plugin path,
 * this list is what Claude Code surfaces to the user — truecast's own tool-grant confirm doesn't run there).
 */
export function composeAgentFile(
  cached: CachedPersona,
  persona: Persona,
  transport: PromptTransport,
): string {
  const name = cached.name;
  const m = persona.manifest;
  const frontmatter = [
    "---",
    `name: ${name}`,
    `description: ${oneFrontmatterLine(m.description ?? `The ${name} persona.`)}`,
    ...(m.modelHint ? [`model: ${oneFrontmatterLine(m.modelHint)}`] : []),
    ...(m.tools && m.tools.length > 0 ? [`tools: ${m.tools.join(", ")}`] : []),
    "---",
  ].join("\n");
  // The version comes from the MANIFEST, not `cached.version`, so both lanes stamp the same string.
  const head = stamp(name, m.version);
  return `${frontmatter}\n\n${head}\n\n${renderSystemPrompt(cached, persona, transport)}\n`;
}

/**
 * Generate the Claude Code `@subagent` surface: `~/.claude/agents/<name>.md` = frontmatter + the
 * composed system prompt. Skills/knowledge are NOT copied anywhere — they are the persona's private
 * craft, Read on demand at an absolute path into this home's store (the body indexes them). Legacy
 * `~/.claude/skills` copies a prior version made are swept here.
 */

export function materialize(
  cached: CachedPersona,
  persona: Persona,
  config: Config,
  ledger: Ledger,
  opts: WriteOptions = {},
): void {
  const name = cached.name;
  const body = composeAgentFile(cached, persona, {
    kind: "subagent",
    truecastHome: config.truecastHome,
  });
  ledger.writeFile(paths.claudeAgent(config, name), body, "agent", opts);

  // sweep any legacy ~/.claude/skills copies a prior truecast version installed (now inert for subagents)
  for (const e of ledger.owned()) {
    if (e.kind === "skill") ledger.removeOwned(e.path);
  }
}
