import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Config } from "../config/index.js";
import { install } from "./index.js";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const personaSrc = join(repoRoot, "personas", "product-manager");

let home: string;
let config: Config;
let project: string;

beforeAll(() => {
  home = mkdtempSync(join(tmpdir(), "tc-install-e2e-"));
  config = {
    truecastHome: join(home, ".truecast"),
    claudeHome: join(home, ".claude"),
    tmpRoot: home,
  };
  project = join(home, "myapp");
  mkdirSync(join(project, ".git"), { recursive: true }); // a git root for locate
});
afterAll(() => rmSync(home, { recursive: true, force: true }));

describe("install — walking skeleton (local path, into temp homes)", () => {
  it("installs the product-manager persona end to end", async () => {
    const result = await install(
      { source: personaSrc, project, cwd: project },
      { config, confirm: () => true },
    );
    expect(result.applied).toBe(true);
    expect(result.plan.persona).toBe("product-manager");
    expect(result.plan.tools).toContain("Read");

    // global cache + current pointer resolve
    const cacheCore = join(config.truecastHome, "personas", "product-manager", "1.0.0", "core");
    expect(existsSync(join(cacheCore, "agent.md"))).toBe(true);
    const currentCore = join(config.truecastHome, "personas", "product-manager", "current", "core");
    expect(existsSync(join(currentCore, "persona.toml"))).toBe(true);

    // generated Claude Code surface
    const agent = join(config.claudeHome, "agents", "product-manager.md");
    expect(existsSync(agent)).toBe(true);
    expect(readFileSync(agent, "utf8")).toContain("GENERATED by truecast");
    const skill = join(config.claudeHome, "skills", "product-manager-run-a-rat", "SKILL.md");
    expect(existsSync(skill)).toBe(true);

    // project: core symlink resolves, instance scaffolded, lock + gitignore written
    const coreLink = join(project, ".truecast", "agents", "product-manager", "core");
    expect(existsSync(join(coreLink, "agent.md"))).toBe(true); // resolves through the symlink
    const mandate = join(
      project,
      ".truecast",
      "agents",
      "product-manager",
      "instance",
      "mandate.md",
    );
    expect(existsSync(mandate)).toBe(true);
    expect(existsSync(join(project, ".truecast", "lock"))).toBe(true);
    expect(readFileSync(join(project, ".gitignore"), "utf8")).toContain(".truecast/agents/*/core");

    // ledger written
    expect(existsSync(join(config.truecastHome, "manifest.json"))).toBe(true);
  });

  it("preserves a hand-edited instance on re-install (B2)", async () => {
    const mandate = join(
      project,
      ".truecast",
      "agents",
      "product-manager",
      "instance",
      "mandate.md",
    );
    const myEdit = "# MY JOB\nGuard against over-engineering in myapp.\n";
    rmSync(mandate, { force: true });
    mkdirSync(dirname(mandate), { recursive: true });
    const { writeFileSync } = await import("node:fs");
    writeFileSync(mandate, myEdit);

    await install({ source: personaSrc, project, cwd: project }, { config, confirm: () => true });
    expect(readFileSync(mandate, "utf8")).toBe(myEdit); // untouched
  });

  it("dry-run writes nothing and returns the plan", async () => {
    const r = await install(
      { source: personaSrc, project, cwd: project, dryRun: true },
      { config },
    );
    expect(r.applied).toBe(false);
    expect(r.plan.writes.length).toBeGreaterThan(0);
  });
});
